### ISSUE TITLE
Same function for promo?

### ISSUE THREAD

**Issue by yxliang01** [Steven-Roberts/chrome-manifest-iconify#1]
Thanks for creating this! It's very helpful! Meanwhile, I think this will be super cool if the same function can be implemented for promo.

Thanks!

**Comment by Steven-Roberts** [comment]
Hi @yxliang01, thanks for the feedback!  One thing to consider is the three promo images each have different aspect ratios so cropping would need to be handled.  Also this process does not need access to the manifest.  For these reasons, I think this idea warrants its own Node package and/or Gulp plugin.  While there are many scenarios where I can see this being useful, I do not have a strong need or the time to tackle this now.

**Comment by yxliang01** [comment]
Right. Indeed, this function would be less useful to promo images. Would you mind if I create the node package for promo which is (heavily) based on this code (if I have time)?

Thanks

**Comment by Steven-Roberts** [comment]
Not at all.  Glad this code can be of use.  That's why it's on Github.

**Comment by yxliang01** [comment]
Cool!
